apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: {{project_name | to_kebab}}
  namespace: default
spec:
  components:
    - name: {{project_name | to_kebab}}
      properties:
        accountId: "870332510631"
        addRevisionLabel: false
        clusterOidc: arn:aws:iam::870332510631:oidc-provider/oidc.eks.sa-east-1.amazonaws.com/id/9BCFFCA3D5ED4A7FADB1AE0C32B2BCC8
        exposeType: ClusterIP
        image: docker.io/stackspot/dotnet-demo-api:10.0.1
        region: {{region_endpoint}}
        targetPort: 5001
      type: microservice
  policies:
    - name: deploy-demo
      type: topology
      properties:
        clusters: ["stackspot-prod"]
        namespace: default 