apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: {{project_name | to_kebab}}
  namespace: default
spec:
  components:
    - name: {{project_name | to_kebab}}
      properties:
        accountId: "401767127224"
        addRevisionLabel: false
        clusterOidc: arn:aws:iam::401767127224:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/01E2AA384A35E5978648E6558BFA59A5
        exposeType: ClusterIP
        image: stackspot/dotnet-demo-api:10.0.1
        region: sa-east-1
        registry: docker.io/
        targetPort: 5001
      type: microservice